import { Request, Response, Router } from 'express';
import { authMiddleWare } from '../../libs/routes';
import validationHandler from '../../libs/routes/validationHandler';
import trainee from './Controller';
import validation from './validation';
const traineeRoute: Router = Router();
traineeRoute.get('/', authMiddleWare('Trainee', 'delete'), trainee.get);
traineeRoute.post('/', authMiddleWare('TRAINEE', 'read'), trainee.create);
traineeRoute.put('/', authMiddleWare('TRAINEE', 'write'), trainee.put);
traineeRoute.delete('/', authMiddleWare('TRAINEE', 'read'), trainee.delete);
export default traineeRoute;
